vehicleproject/vehicleapp/urls.py
from django.urls import path
from . import views
app_name='vehicleapp'
urlpatterns = [

    path('',views.index, name='index'),
    path('vehicle/<int:vehicle_id>/',views.detail,name='detail'),
    path('add/',views.add_vehicle,name='add_vehicle'),
    path('update/<int:id>/', views.update,name='update'),
    path('delete/<int:id>/', views.delete,name='delete')
]

vehicleproject/vehicleproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("vehicleapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicleproject/vehicleapp/models.py
from django.db import models

# Create your models here.
class Vehicle(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

vehicleproject/vehicleapp/forms.py
from django import forms
from .models import Vehicle

class VehicleForm(forms.ModelForm):
    class Meta:
        model=Vehicle
        fields=['name','desc','year','img']

vehicleproject/vehicleapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Vehicle
from . forms import VehicleForm

# Create your views here.

def index(request):
    vehicle=Vehicle.objects.all()
    context={
        'vehicle_list':vehicle
    }
    return render(request, 'index.html',context)

def detail(request,vehicle_id):
    vehicle=Vehicle.objects.get(id=vehicle_id)
    return render(request,"detail.html",{'vehicle':vehicle})

def add_vehicle(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        vehicle=Vehicle(name=name, desc=desc, year=year, img=img)
        vehicle.save()

    return render(request,'add.html')

def update(request,id):
    vehicle=Vehicle.objects.get(id=id)
    form=VehicleForm(request.POST or None, request.FILES, instance=vehicle)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'edit.html', {'form':form, 'vehicle':vehicle})

def delete(request, id):
    if request.method=='POST':
        vehicle=Vehicle.objects.get(id=id)
        vehicle.delete()
        return redirect('/')

    return render(request, 'delete.html')

vehicleproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Vehicle Name">
    <input type="text" name="desc" placeholder="Enter the Vehicle Description">
    <input type="text" name="year" placeholder="Enter the Vehicle Year">
    <input type="file" name="img">
    <input type="submit">

</form>

{% endblock %}

vehicleproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    VEHICLE INFORMATION
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

vehicleproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Do you want to delete this Vehicle details
  <input type="submit">
</form>

vehicleproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<img src="{{vehicle.img.url}}"><br>
{{vehicle.name}}<br>
{{vehicle.desc}}<br>
{{vehicle.year}}<br>
<a class="btn btn-warning" href="{% url 'vehicleapp:update' vehicle.id %}">update</a><br>
<a class="btn btn-danger" href="{% url 'vehicleapp:delete' vehicle.id %}">delete</a><br>
{% endblock %}

vehicleproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

vehicleproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in vehicle_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="180px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'vehicleapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}